### ISSUE TITLE
Invalid content /en/shelley/get-started/wallet/

### ISSUE THREAD

**Issue by jmchapman** [cardano-foundation/testnets-cardano-org#236]
**Where does the issue occur?**
https://testnets.cardano.org/en/shelley/get-started/wallet/

**Describe the issue**

For the windows version this page shows that Windows 8.1 and Windows 10 are supported.

For the Mac and Linux version it doesn't say which versions/distributions are supported.

I can imagine that there is a trade-off between having a polished/easy to navigate page vs having lots of information but I wasn't able to find this information at all.

**Expected changes**
Link to list of officially supported OS versions or display some information on this page.

**Comment by olgahryniuk** [comment]
Thank you for your input. This issue is now fixed, supported versions can be found here:
https://developers.cardano.org/en/testnets/cardano/get-started/wallet/

**Comment by jmchapman** [comment]
You're welcome - but the information is still not shown on that page - it says "Windows 8.1 and 10" and only "MacOS" and "Linux"

**Comment by olgahryniuk** [comment]
We have "Mac OS 64 bit, Version: 3.2.0" and "Linux 64 bit, Version: 3.2.0". Is that the information you're looking for?

**Comment by jmchapman** [comment]
I was looking for the versions of the  MacOS or Linux operating systems that are supported.
e.g., MacOS 10.13 or above and for Linux I am not sure how portable the binary is and which distributions it is expected to run on e.g., Debian version x or above, Ubuntu version y or above etc, or whether it requires certain libraries etc.

I think 3.2.0 refers to the Cardano version and 64-bit does narrow down the OS support but isn't the whole of the story.

**Comment by olgahryniuk** [comment]
Thanks for the clarification, I'll be finding out details from the development team.

**Comment by jmchapman** [comment]
Thanks!

**Comment by olgahryniuk** [comment]
Hello, James! These requirements apply for Daedalus mainnet, testnet and flight as well:
https://iohk.zendesk.com/hc/en-us/articles/360010496553-Daedalus-System-Requirements 
The recent PR has been created to add this information, it will soon be visible. Hope that helps! If you have any specific questions, you can also contact our support team. Thanks!
